# Generated by Django 2.0.6 on 2018-06-23 17:58

import dialogbot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
            },
            bases=(dialogbot.models.Creation, models.Model),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.TextField()),
                ('team_id', models.TextField(db_index=True)),
                ('team_name', models.CharField(max_length=100)),
                ('user_access_token', models.TextField()),
                ('bot_access_token', models.TextField()),
            ],
            options={
                'verbose_name': 'Team',
            },
            bases=(dialogbot.models.Creation, models.Model),
        ),
    ]
